-- Removes only test rows created by the work-order SQL E2E suite; seed data is retained.
IF DB_NAME() <> N'G2ERP_DEV_LOCAL_TEST'
    THROW 51000, 'This script may run only against G2ERP_DEV_LOCAL_TEST.', 1;

SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;
    DELETE FROM POC.PRT_WOPROC WHERE NO_WO LIKE N'E2E-WO-SQL-%' OR NO_WO LIKE N'E2E-WO-DUP-%';
    DELETE FROM POC.PRT_WO WHERE NO_WO LIKE N'E2E-WO-SQL-%' OR NO_WO LIKE N'E2E-WO-DUP-%';
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
