SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID(N'POC.DOC_NO_COUNTER', N'U') IS NULL
BEGIN
    CREATE TABLE POC.DOC_NO_COUNTER
    (
        CD_FIRM nvarchar(10) NOT NULL,
        DOC_TYPE varchar(3) NOT NULL,
        YEAR_MONTH char(6) NOT NULL,
        LAST_SERIAL int NOT NULL,
        TM_AMD datetime2(0) NOT NULL CONSTRAINT DF_DOC_NO_COUNTER_TM_AMD DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_DOC_NO_COUNTER PRIMARY KEY (CD_FIRM, DOC_TYPE, YEAR_MONTH),
        CONSTRAINT CK_DOC_NO_COUNTER_TYPE CHECK (DOC_TYPE IN ('SOR', 'POR', 'WMO')),
        CONSTRAINT CK_DOC_NO_COUNTER_MONTH CHECK (YEAR_MONTH LIKE '[12][0-9][0-9][0-9][01][0-9]'),
        CONSTRAINT CK_DOC_NO_COUNTER_SERIAL CHECK (LAST_SERIAL BETWEEN 1 AND 9999)
    );
END;

;WITH ExistingNumbers AS
(
    SELECT CD_FIRM, 'SOR' AS DOC_TYPE, SUBSTRING(NO_SO, 4, 6) AS YEAR_MONTH,
           MAX(TRY_CONVERT(int, RIGHT(NO_SO, 4))) AS LAST_SERIAL
    FROM POC.SAL_SOH
    WHERE LEN(NO_SO) = 13 AND NO_SO LIKE 'SOR[12][0-9][0-9][0-9][01][0-9][0-9][0-9][0-9][0-9]'
    GROUP BY CD_FIRM, SUBSTRING(NO_SO, 4, 6)
    UNION ALL
    SELECT CD_FIRM, 'POR', SUBSTRING(NO_PO, 4, 6), MAX(TRY_CONVERT(int, RIGHT(NO_PO, 4)))
    FROM POC.PUR_POH
    WHERE LEN(NO_PO) = 13 AND NO_PO LIKE 'POR[12][0-9][0-9][0-9][01][0-9][0-9][0-9][0-9][0-9]'
    GROUP BY CD_FIRM, SUBSTRING(NO_PO, 4, 6)
    UNION ALL
    SELECT CD_FIRM, 'WMO', SUBSTRING(NO_WO, 4, 6), MAX(TRY_CONVERT(int, RIGHT(NO_WO, 4)))
    FROM POC.PRT_WO
    WHERE LEN(NO_WO) = 13 AND NO_WO LIKE 'WMO[12][0-9][0-9][0-9][01][0-9][0-9][0-9][0-9][0-9]'
    GROUP BY CD_FIRM, SUBSTRING(NO_WO, 4, 6)
)
MERGE POC.DOC_NO_COUNTER WITH (HOLDLOCK) AS Target
USING ExistingNumbers AS Source
ON Target.CD_FIRM = Source.CD_FIRM
AND Target.DOC_TYPE = Source.DOC_TYPE
AND Target.YEAR_MONTH = Source.YEAR_MONTH
WHEN MATCHED AND Target.LAST_SERIAL < Source.LAST_SERIAL THEN
    UPDATE SET LAST_SERIAL = Source.LAST_SERIAL, TM_AMD = SYSUTCDATETIME()
WHEN NOT MATCHED THEN
    INSERT (CD_FIRM, DOC_TYPE, YEAR_MONTH, LAST_SERIAL)
    VALUES (Source.CD_FIRM, Source.DOC_TYPE, Source.YEAR_MONTH, Source.LAST_SERIAL);

COMMIT TRANSACTION;
