-- FINAL-UAT-202608 sales conversion schema. Local test database only.
IF DB_NAME() <> N'G2ERP_DEV_LOCAL_TEST'
    THROW 51000, 'This script may run only against G2ERP_DEV_LOCAL_TEST.', 1;

SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET ARITHABORT ON;
SET NUMERIC_ROUNDABORT OFF;
BEGIN TRANSACTION;

IF COL_LENGTH(N'POC.SAL_SOH', N'ID_SOH') IS NULL
    ALTER TABLE POC.SAL_SOH ADD ID_SOH uniqueidentifier NOT NULL CONSTRAINT DF_SAL_SOH_ID DEFAULT NEWSEQUENTIALID() WITH VALUES;
IF COL_LENGTH(N'POC.SAL_SOL', N'ID_SOL') IS NULL
    ALTER TABLE POC.SAL_SOL ADD ID_SOL uniqueidentifier NOT NULL CONSTRAINT DF_SAL_SOL_ID DEFAULT NEWSEQUENTIALID() WITH VALUES;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'POC.SAL_SOH') AND name=N'UX_SAL_SOH_ID') EXEC(N'CREATE UNIQUE INDEX UX_SAL_SOH_ID ON POC.SAL_SOH(ID_SOH)');
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'POC.SAL_SOL') AND name=N'UX_SAL_SOL_ID') EXEC(N'CREATE UNIQUE INDEX UX_SAL_SOL_ID ON POC.SAL_SOL(ID_SOL)');

IF COL_LENGTH(N'POC.PUR_POH', N'ID_POH') IS NULL ALTER TABLE POC.PUR_POH ADD ID_POH uniqueidentifier NOT NULL CONSTRAINT DF_PUR_POH_ID DEFAULT NEWSEQUENTIALID() WITH VALUES;
IF COL_LENGTH(N'POC.PUR_POH', N'ID_CONVERSION_REQUEST') IS NULL ALTER TABLE POC.PUR_POH ADD ID_CONVERSION_REQUEST uniqueidentifier NULL;
IF COL_LENGTH(N'POC.PUR_POL', N'ID_POL') IS NULL ALTER TABLE POC.PUR_POL ADD ID_POL uniqueidentifier NOT NULL CONSTRAINT DF_PUR_POL_ID DEFAULT NEWSEQUENTIALID() WITH VALUES;
IF COL_LENGTH(N'POC.PUR_POL', N'ID_POH') IS NULL
BEGIN
    ALTER TABLE POC.PUR_POL ADD ID_POH uniqueidentifier NULL;
    EXEC(N'UPDATE target SET ID_POH=header.ID_POH FROM POC.PUR_POL target INNER JOIN POC.PUR_POH header ON header.CD_FIRM=target.CD_FIRM AND header.NO_PO=target.NO_PO');
    EXEC(N'ALTER TABLE POC.PUR_POL ALTER COLUMN ID_POH uniqueidentifier NOT NULL');
END;
IF COL_LENGTH(N'POC.PUR_POL', N'ID_SOURCE_SOH') IS NULL ALTER TABLE POC.PUR_POL ADD ID_SOURCE_SOH uniqueidentifier NULL;
IF COL_LENGTH(N'POC.PUR_POL', N'ID_SOURCE_SOL') IS NULL ALTER TABLE POC.PUR_POL ADD ID_SOURCE_SOL uniqueidentifier NULL;
IF COL_LENGTH(N'POC.PUR_POL', N'NO_SOURCE_SO') IS NULL ALTER TABLE POC.PUR_POL ADD NO_SOURCE_SO varchar(30) NULL;
IF COL_LENGTH(N'POC.PUR_POL', N'NO_SOURCE_LINE') IS NULL ALTER TABLE POC.PUR_POL ADD NO_SOURCE_LINE int NULL;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'POC.PUR_POH') AND name=N'UX_PUR_POH_ID') EXEC(N'CREATE UNIQUE INDEX UX_PUR_POH_ID ON POC.PUR_POH(ID_POH)');
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'POC.PUR_POH') AND name=N'UX_PUR_POH_CONVERSION_REQUEST') EXEC(N'CREATE UNIQUE INDEX UX_PUR_POH_CONVERSION_REQUEST ON POC.PUR_POH(ID_CONVERSION_REQUEST) WHERE ID_CONVERSION_REQUEST IS NOT NULL');
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'POC.PUR_POL') AND name=N'UX_PUR_POL_ID') EXEC(N'CREATE UNIQUE INDEX UX_PUR_POL_ID ON POC.PUR_POL(ID_POL)');
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'POC.PUR_POL') AND name=N'IX_PUR_POL_SOURCE') EXEC(N'CREATE INDEX IX_PUR_POL_SOURCE ON POC.PUR_POL(ID_SOURCE_SOL, NO_SOURCE_SO, NO_SOURCE_LINE)');
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_PUR_POL_POH_ID') EXEC(N'ALTER TABLE POC.PUR_POL ADD CONSTRAINT FK_PUR_POL_POH_ID FOREIGN KEY(ID_POH) REFERENCES POC.PUR_POH(ID_POH)');
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_PUR_POL_SOURCE_SOH') EXEC(N'ALTER TABLE POC.PUR_POL ADD CONSTRAINT FK_PUR_POL_SOURCE_SOH FOREIGN KEY(ID_SOURCE_SOH) REFERENCES POC.SAL_SOH(ID_SOH)');
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_PUR_POL_SOURCE_SOL') EXEC(N'ALTER TABLE POC.PUR_POL ADD CONSTRAINT FK_PUR_POL_SOURCE_SOL FOREIGN KEY(ID_SOURCE_SOL) REFERENCES POC.SAL_SOL(ID_SOL)');

IF COL_LENGTH(N'POC.PRT_WO', N'ID_WO') IS NULL ALTER TABLE POC.PRT_WO ADD ID_WO uniqueidentifier NOT NULL CONSTRAINT DF_PRT_WO_ID DEFAULT NEWSEQUENTIALID() WITH VALUES;
IF COL_LENGTH(N'POC.PRT_WO', N'ID_SOURCE_SOH') IS NULL ALTER TABLE POC.PRT_WO ADD ID_SOURCE_SOH uniqueidentifier NULL;
IF COL_LENGTH(N'POC.PRT_WO', N'ID_SOURCE_SOL') IS NULL ALTER TABLE POC.PRT_WO ADD ID_SOURCE_SOL uniqueidentifier NULL;
IF COL_LENGTH(N'POC.PRT_WO', N'NO_SOURCE_SO') IS NULL ALTER TABLE POC.PRT_WO ADD NO_SOURCE_SO varchar(30) NULL;
IF COL_LENGTH(N'POC.PRT_WO', N'NO_SOURCE_LINE') IS NULL ALTER TABLE POC.PRT_WO ADD NO_SOURCE_LINE int NULL;
IF COL_LENGTH(N'POC.PRT_WO', N'ID_CONVERSION_REQUEST') IS NULL ALTER TABLE POC.PRT_WO ADD ID_CONVERSION_REQUEST uniqueidentifier NULL;
IF COL_LENGTH(N'POC.PRT_WOPROC', N'ID_WOPROC') IS NULL ALTER TABLE POC.PRT_WOPROC ADD ID_WOPROC uniqueidentifier NOT NULL CONSTRAINT DF_PRT_WOPROC_ID DEFAULT NEWSEQUENTIALID() WITH VALUES;
IF COL_LENGTH(N'POC.PRT_WOPROC', N'ID_WO') IS NULL
BEGIN
    ALTER TABLE POC.PRT_WOPROC ADD ID_WO uniqueidentifier NULL;
    EXEC(N'UPDATE target SET ID_WO=header.ID_WO FROM POC.PRT_WOPROC target INNER JOIN POC.PRT_WO header ON header.CD_FIRM=target.CD_FIRM AND header.NO_WO=target.NO_WO');
    EXEC(N'ALTER TABLE POC.PRT_WOPROC ALTER COLUMN ID_WO uniqueidentifier NOT NULL');
END;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'POC.PRT_WO') AND name=N'UX_PRT_WO_ID') EXEC(N'CREATE UNIQUE INDEX UX_PRT_WO_ID ON POC.PRT_WO(ID_WO)');
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'POC.PRT_WO') AND name=N'UX_PRT_WO_CONVERSION_REQUEST') EXEC(N'CREATE UNIQUE INDEX UX_PRT_WO_CONVERSION_REQUEST ON POC.PRT_WO(ID_CONVERSION_REQUEST) WHERE ID_CONVERSION_REQUEST IS NOT NULL');
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'POC.PRT_WO') AND name=N'IX_PRT_WO_SOURCE') EXEC(N'CREATE INDEX IX_PRT_WO_SOURCE ON POC.PRT_WO(ID_SOURCE_SOL, NO_SOURCE_SO, NO_SOURCE_LINE)');
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'POC.PRT_WOPROC') AND name=N'UX_PRT_WOPROC_ID') EXEC(N'CREATE UNIQUE INDEX UX_PRT_WOPROC_ID ON POC.PRT_WOPROC(ID_WOPROC)');
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_PRT_WO_SOURCE_SOH') EXEC(N'ALTER TABLE POC.PRT_WO ADD CONSTRAINT FK_PRT_WO_SOURCE_SOH FOREIGN KEY(ID_SOURCE_SOH) REFERENCES POC.SAL_SOH(ID_SOH)');
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_PRT_WO_SOURCE_SOL') EXEC(N'ALTER TABLE POC.PRT_WO ADD CONSTRAINT FK_PRT_WO_SOURCE_SOL FOREIGN KEY(ID_SOURCE_SOL) REFERENCES POC.SAL_SOL(ID_SOL)');
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_PRT_WOPROC_WO_ID') EXEC(N'ALTER TABLE POC.PRT_WOPROC ADD CONSTRAINT FK_PRT_WOPROC_WO_ID FOREIGN KEY(ID_WO) REFERENCES POC.PRT_WO(ID_WO)');

IF OBJECT_ID(N'POC.MST_BOM_H', N'U') IS NULL CREATE TABLE POC.MST_BOM_H(ID_BOM uniqueidentifier NOT NULL CONSTRAINT DF_MST_BOM_H_ID DEFAULT NEWSEQUENTIALID(),CD_FIRM nvarchar(10) NOT NULL,CD_ITEM nvarchar(30) NOT NULL,NO_VERSION nvarchar(20) NOT NULL,YN_APPROVED char(1) NOT NULL,DT_VALID_FROM date NOT NULL,DT_VALID_TO date NULL,CD_USER_REG nvarchar(50) NOT NULL,TM_REG datetime2(3) NOT NULL,CONSTRAINT PK_MST_BOM_H PRIMARY KEY(ID_BOM),CONSTRAINT UQ_MST_BOM_H UNIQUE(CD_FIRM,CD_ITEM,NO_VERSION),CONSTRAINT CK_MST_BOM_H_APPROVED CHECK(YN_APPROVED IN('Y','N')));
IF OBJECT_ID(N'POC.MST_BOM_L', N'U') IS NULL CREATE TABLE POC.MST_BOM_L(ID_BOM_LINE uniqueidentifier NOT NULL CONSTRAINT DF_MST_BOM_L_ID DEFAULT NEWSEQUENTIALID(),ID_BOM uniqueidentifier NOT NULL,NO_LINE int NOT NULL,CD_COMPONENT nvarchar(30) NOT NULL,NM_COMPONENT nvarchar(100) NOT NULL,UNIT_COMPONENT nvarchar(20) NOT NULL,QT_BASE decimal(18,6) NOT NULL,CONSTRAINT PK_MST_BOM_L PRIMARY KEY(ID_BOM_LINE),CONSTRAINT UQ_MST_BOM_L UNIQUE(ID_BOM,NO_LINE),CONSTRAINT FK_MST_BOM_L_H FOREIGN KEY(ID_BOM) REFERENCES POC.MST_BOM_H(ID_BOM),CONSTRAINT CK_MST_BOM_L_QTY CHECK(QT_BASE>0));
IF OBJECT_ID(N'POC.MST_ROUTING_H', N'U') IS NULL CREATE TABLE POC.MST_ROUTING_H(ID_ROUTING uniqueidentifier NOT NULL CONSTRAINT DF_MST_ROUTING_H_ID DEFAULT NEWSEQUENTIALID(),CD_FIRM nvarchar(10) NOT NULL,CD_ITEM nvarchar(30) NOT NULL,NO_VERSION nvarchar(20) NOT NULL,YN_APPROVED char(1) NOT NULL,DT_VALID_FROM date NOT NULL,DT_VALID_TO date NULL,CD_USER_REG nvarchar(50) NOT NULL,TM_REG datetime2(3) NOT NULL,CONSTRAINT PK_MST_ROUTING_H PRIMARY KEY(ID_ROUTING),CONSTRAINT UQ_MST_ROUTING_H UNIQUE(CD_FIRM,CD_ITEM,NO_VERSION),CONSTRAINT CK_MST_ROUTING_H_APPROVED CHECK(YN_APPROVED IN('Y','N')));
IF OBJECT_ID(N'POC.MST_ROUTING_OP', N'U') IS NULL CREATE TABLE POC.MST_ROUTING_OP(ID_ROUTING_OP uniqueidentifier NOT NULL CONSTRAINT DF_MST_ROUTING_OP_ID DEFAULT NEWSEQUENTIALID(),ID_ROUTING uniqueidentifier NOT NULL,NO_SEQ int NOT NULL,CD_PROC nvarchar(30) NOT NULL,NM_PROC nvarchar(100) NOT NULL,CD_LINE nvarchar(30) NOT NULL,NM_LINE nvarchar(100) NOT NULL,TM_BASE_MIN decimal(18,4) NOT NULL,CONSTRAINT PK_MST_ROUTING_OP PRIMARY KEY(ID_ROUTING_OP),CONSTRAINT UQ_MST_ROUTING_OP UNIQUE(ID_ROUTING,NO_SEQ),CONSTRAINT FK_MST_ROUTING_OP_H FOREIGN KEY(ID_ROUTING) REFERENCES POC.MST_ROUTING_H(ID_ROUTING),CONSTRAINT CK_MST_ROUTING_OP_TIME CHECK(TM_BASE_MIN>=0));
IF OBJECT_ID(N'POC.MST_SUPPLIER_ITEM_PRICE', N'U') IS NULL CREATE TABLE POC.MST_SUPPLIER_ITEM_PRICE(ID_PRICE uniqueidentifier NOT NULL CONSTRAINT DF_MST_SUPPLIER_ITEM_PRICE_ID DEFAULT NEWSEQUENTIALID(),CD_FIRM varchar(10) NOT NULL,CD_SUPPLIER varchar(20) NOT NULL,CD_ITEM varchar(30) NOT NULL,CD_CURRENCY varchar(10) NOT NULL,UM_PO decimal(19,4) NOT NULL,DT_VALID_FROM date NOT NULL,DT_VALID_TO date NULL,YN_USE char(1) NOT NULL,CONSTRAINT PK_MST_SUPPLIER_ITEM_PRICE PRIMARY KEY(ID_PRICE),CONSTRAINT UQ_MST_SUPPLIER_ITEM_PRICE UNIQUE(CD_FIRM,CD_SUPPLIER,CD_ITEM,CD_CURRENCY,DT_VALID_FROM),CONSTRAINT CK_MST_SUPPLIER_ITEM_PRICE_USE CHECK(YN_USE IN('Y','N')),CONSTRAINT CK_MST_SUPPLIER_ITEM_PRICE_AMOUNT CHECK(UM_PO>=0));

IF OBJECT_ID(N'POC.PRT_WOBILL', N'U') IS NULL CREATE TABLE POC.PRT_WOBILL(ID_WOBILL uniqueidentifier NOT NULL CONSTRAINT DF_PRT_WOBILL_ID DEFAULT NEWSEQUENTIALID(),ID_WO uniqueidentifier NOT NULL,CD_FIRM nvarchar(10) NOT NULL,NO_WO nvarchar(30) NOT NULL,NO_BOM_LINE int NOT NULL,CD_COMPONENT nvarchar(30) NOT NULL,NM_COMPONENT nvarchar(100) NOT NULL,UNIT_COMPONENT nvarchar(20) NOT NULL,QT_BASE decimal(18,6) NOT NULL,QT_REQUIRED decimal(18,6) NOT NULL,CD_USER_REG nvarchar(50) NOT NULL,TM_REG datetime2(3) NOT NULL,CONSTRAINT PK_PRT_WOBILL PRIMARY KEY(ID_WOBILL),CONSTRAINT UQ_PRT_WOBILL UNIQUE(ID_WO,NO_BOM_LINE),CONSTRAINT FK_PRT_WOBILL_WO_ID FOREIGN KEY(ID_WO) REFERENCES POC.PRT_WO(ID_WO),CONSTRAINT FK_PRT_WOBILL_WO FOREIGN KEY(CD_FIRM,NO_WO) REFERENCES POC.PRT_WO(CD_FIRM,NO_WO),CONSTRAINT CK_PRT_WOBILL_QTY CHECK(QT_BASE>0 AND QT_REQUIRED>0));
IF OBJECT_ID(N'POC.DOC_CONVERSION_REQUEST', N'U') IS NULL CREATE TABLE POC.DOC_CONVERSION_REQUEST(ID_REQUEST uniqueidentifier NOT NULL,CD_FIRM nvarchar(10) NOT NULL,REQUEST_KEY nvarchar(100) NOT NULL,CONVERSION_TYPE varchar(3) NOT NULL,ID_TARGET uniqueidentifier NOT NULL,NO_TARGET nvarchar(30) NOT NULL,ST_REQUEST nvarchar(20) NOT NULL,CD_USER_REG nvarchar(50) NOT NULL,TM_REG datetime2(3) NOT NULL,CONSTRAINT PK_DOC_CONVERSION_REQUEST PRIMARY KEY(ID_REQUEST),CONSTRAINT UQ_DOC_CONVERSION_REQUEST UNIQUE(CD_FIRM,CONVERSION_TYPE,REQUEST_KEY),CONSTRAINT CK_DOC_CONVERSION_TYPE CHECK(CONVERSION_TYPE IN('POR','WMO')));
IF OBJECT_ID(N'POC.DOC_CONVERSION_REQUEST_LINE', N'U') IS NULL CREATE TABLE POC.DOC_CONVERSION_REQUEST_LINE(ID_REQUEST_LINE uniqueidentifier NOT NULL CONSTRAINT DF_DOC_CONVERSION_REQUEST_LINE_ID DEFAULT NEWSEQUENTIALID(),ID_REQUEST uniqueidentifier NOT NULL,ID_SOURCE_SOH uniqueidentifier NOT NULL,ID_SOURCE_SOL uniqueidentifier NOT NULL,NO_SOURCE_SO nvarchar(30) NOT NULL,NO_SOURCE_LINE int NOT NULL,QT_CONVERTED decimal(18,4) NOT NULL,CONSTRAINT PK_DOC_CONVERSION_REQUEST_LINE PRIMARY KEY(ID_REQUEST_LINE),CONSTRAINT UQ_DOC_CONVERSION_REQUEST_LINE UNIQUE(ID_REQUEST,ID_SOURCE_SOL),CONSTRAINT FK_DOC_CONVERSION_REQUEST_LINE_H FOREIGN KEY(ID_REQUEST) REFERENCES POC.DOC_CONVERSION_REQUEST(ID_REQUEST),CONSTRAINT FK_DOC_CONVERSION_REQUEST_LINE_SOH FOREIGN KEY(ID_SOURCE_SOH) REFERENCES POC.SAL_SOH(ID_SOH),CONSTRAINT FK_DOC_CONVERSION_REQUEST_LINE_SOL FOREIGN KEY(ID_SOURCE_SOL) REFERENCES POC.SAL_SOL(ID_SOL),CONSTRAINT CK_DOC_CONVERSION_REQUEST_LINE_QTY CHECK(QT_CONVERTED>0));

COMMIT TRANSACTION;
