-- FINAL-UAT-202608 fictional conversion masters. Local test database only.
IF DB_NAME() <> N'G2ERP_DEV_LOCAL_TEST' THROW 51000, 'This script may run only against G2ERP_DEV_LOCAL_TEST.', 1;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

MERGE POC.MA_PARTNER AS target USING (VALUES
    ('1000','UAT-SUP-01',N'세림정밀 테스트 공급사','000-00-20801','Y'),
    ('1000','UAT-SUP-02',N'한빛전자 테스트 공급사','000-00-20802','Y')
) source(CD_FIRM,CD_PARTNER,NM_PARTNER,NO_COMPANY,YN_USE)
ON target.CD_FIRM=source.CD_FIRM AND target.CD_PARTNER=source.CD_PARTNER
WHEN MATCHED THEN UPDATE SET NM_PARTNER=source.NM_PARTNER,NO_COMPANY=source.NO_COMPANY,YN_USE=source.YN_USE
WHEN NOT MATCHED THEN INSERT VALUES(source.CD_FIRM,source.CD_PARTNER,source.NM_PARTNER,source.NO_COMPANY,source.YN_USE);

MERGE POC.MA_WH AS target USING (VALUES ('1000','UAT-WH-01',N'FINAL UAT 자재창고','Y')) source(CD_FIRM,CD_WH,NM_WH,YN_USE)
ON target.CD_FIRM=source.CD_FIRM AND target.CD_WH=source.CD_WH
WHEN MATCHED THEN UPDATE SET NM_WH=source.NM_WH,YN_USE=source.YN_USE
WHEN NOT MATCHED THEN INSERT VALUES(source.CD_FIRM,source.CD_WH,source.NM_WH,source.YN_USE);

MERGE POC.MA_ITEM AS target USING (VALUES
    ('1000','UAT-FG-01',N'220V 서보드라이브 모듈',N'FINAL-UAT-FG','EA','Y'),
    ('1000','UAT-RM-01',N'알루미늄 하우징',N'FINAL-UAT-RM01','EA','Y'),
    ('1000','UAT-RM-02',N'모터 드라이브 PCB',N'FINAL-UAT-RM02','EA','Y'),
    ('1000','UAT-RM-03',N'정밀 베어링',N'FINAL-UAT-RM03','EA','Y'),
    ('1000','UAT-RM-04',N'체결부품 세트',N'FINAL-UAT-RM04','SET','Y'),
    ('1000','UAT-RM-05',N'포장재',N'FINAL-UAT-RM05','SET','Y')
) source(CD_FIRM,CD_ITEM,NM_ITEM,STND_ITEM,UNIT_ITEM,YN_USE)
ON target.CD_FIRM=source.CD_FIRM AND target.CD_ITEM=source.CD_ITEM
WHEN MATCHED THEN UPDATE SET NM_ITEM=source.NM_ITEM,STND_ITEM=source.STND_ITEM,UNIT_ITEM=source.UNIT_ITEM,YN_USE=source.YN_USE
WHEN NOT MATCHED THEN INSERT VALUES(source.CD_FIRM,source.CD_ITEM,source.NM_ITEM,source.STND_ITEM,source.UNIT_ITEM,source.YN_USE);

MERGE POC.MST_PRODUCTION_LINE AS target USING (VALUES
    ('1000','LINE-A',N'조립 작업장','Y'),
    ('1000','LINE-C',N'검사 작업장','Y'),
    ('1000','LINE-D',N'포장 작업장','Y')
) source(CD_FIRM,CD_LINE,NM_LINE,YN_USE)
ON target.CD_FIRM=source.CD_FIRM AND target.CD_LINE=source.CD_LINE
WHEN MATCHED THEN UPDATE SET NM_LINE=source.NM_LINE,YN_USE=source.YN_USE,CD_USER_AMD=N'FINAL-UAT-202608',TM_AMD=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT(CD_FIRM,CD_LINE,NM_LINE,YN_USE,CD_USER_REG,TM_REG,CD_USER_AMD,TM_AMD) VALUES(source.CD_FIRM,source.CD_LINE,source.NM_LINE,source.YN_USE,N'FINAL-UAT-202608',SYSUTCDATETIME(),N'FINAL-UAT-202608',SYSUTCDATETIME());

MERGE POC.MST_PROCESS AS target USING (VALUES
    ('1000','PROC-010',N'가공',10,'Y'),
    ('1000','PROC-020',N'조립',20,'Y'),
    ('1000','PROC-030',N'전기검사',30,'Y'),
    ('1000','PROC-040',N'최종검사',40,'Y'),
    ('1000','PROC-050',N'포장',50,'Y')
) source(CD_FIRM,CD_PROC,NM_PROC,NO_SEQ,YN_USE)
ON target.CD_FIRM=source.CD_FIRM AND target.CD_PROC=source.CD_PROC
WHEN MATCHED THEN UPDATE SET NM_PROC=source.NM_PROC,NO_SEQ=source.NO_SEQ,YN_USE=source.YN_USE,CD_USER_AMD=N'FINAL-UAT-202608',TM_AMD=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT(CD_FIRM,CD_PROC,NM_PROC,NO_SEQ,YN_USE,CD_USER_REG,TM_REG,CD_USER_AMD,TM_AMD) VALUES(source.CD_FIRM,source.CD_PROC,source.NM_PROC,source.NO_SEQ,source.YN_USE,N'FINAL-UAT-202608',SYSUTCDATETIME(),N'FINAL-UAT-202608',SYSUTCDATETIME());

DECLARE @bom uniqueidentifier=(SELECT ID_BOM FROM POC.MST_BOM_H WHERE CD_FIRM=N'1000' AND CD_ITEM=N'ITM-1001' AND NO_VERSION=N'FINAL-UAT-1');
IF @bom IS NULL
BEGIN
    SET @bom=NEWID();
    INSERT POC.MST_BOM_H(ID_BOM,CD_FIRM,CD_ITEM,NO_VERSION,YN_APPROVED,DT_VALID_FROM,DT_VALID_TO,CD_USER_REG,TM_REG) VALUES(@bom,N'1000',N'ITM-1001',N'FINAL-UAT-1','Y','2026-01-01',NULL,N'FINAL-UAT-202608',SYSUTCDATETIME());
END;
IF NOT EXISTS(SELECT 1 FROM POC.MST_BOM_L WHERE ID_BOM=@bom)
    INSERT POC.MST_BOM_L(ID_BOM_LINE,ID_BOM,NO_LINE,CD_COMPONENT,NM_COMPONENT,UNIT_COMPONENT,QT_BASE) VALUES
    (NEWID(),@bom,10,N'ITM-2102',N'알루미늄 하우징',N'EA',1),(NEWID(),@bom,20,N'ITM-1204',N'모터 드라이브 PCB',N'EA',1),(NEWID(),@bom,30,N'ITM-1410',N'제어용 케이블 세트',N'SET',1);

DECLARE @routing uniqueidentifier=(SELECT ID_ROUTING FROM POC.MST_ROUTING_H WHERE CD_FIRM=N'1000' AND CD_ITEM=N'ITM-1001' AND NO_VERSION=N'FINAL-UAT-1');
IF @routing IS NULL
BEGIN
    SET @routing=NEWID();
    INSERT POC.MST_ROUTING_H(ID_ROUTING,CD_FIRM,CD_ITEM,NO_VERSION,YN_APPROVED,DT_VALID_FROM,DT_VALID_TO,CD_USER_REG,TM_REG) VALUES(@routing,N'1000',N'ITM-1001',N'FINAL-UAT-1','Y','2026-01-01',NULL,N'FINAL-UAT-202608',SYSUTCDATETIME());
END;
IF NOT EXISTS(SELECT 1 FROM POC.MST_ROUTING_OP WHERE ID_ROUTING=@routing)
    INSERT POC.MST_ROUTING_OP(ID_ROUTING_OP,ID_ROUTING,NO_SEQ,CD_PROC,NM_PROC,CD_LINE,NM_LINE,TM_BASE_MIN) VALUES
    (NEWID(),@routing,10,N'PROC-010',N'자재 준비',N'LINE-A',N'조립 1라인',10),(NEWID(),@routing,20,N'PROC-020',N'조립',N'LINE-A',N'조립 1라인',30),(NEWID(),@routing,30,N'PROC-030',N'전기검사',N'LINE-C',N'검사 라인',15),(NEWID(),@routing,40,N'PROC-040',N'최종검사',N'LINE-C',N'검사 라인',15),(NEWID(),@routing,50,N'PROC-050',N'포장',N'LINE-D',N'포장 라인',10);

IF NOT EXISTS(SELECT 1 FROM POC.MST_SUPPLIER_ITEM_PRICE WHERE CD_FIRM='1000' AND CD_SUPPLIER='UAT-SUP-01' AND CD_ITEM='ITM-1001' AND CD_CURRENCY='KRW' AND DT_VALID_FROM='2026-01-01')
    INSERT POC.MST_SUPPLIER_ITEM_PRICE(ID_PRICE,CD_FIRM,CD_SUPPLIER,CD_ITEM,CD_CURRENCY,UM_PO,DT_VALID_FROM,DT_VALID_TO,YN_USE) VALUES(NEWID(),'1000','UAT-SUP-01','ITM-1001','KRW',180000,'2026-01-01',NULL,'Y');

COMMIT TRANSACTION;
