using System.Data;
using G2Erp.Api.Domain;
using G2Erp.Api.Services;
using Microsoft.Data.SqlClient;

namespace G2Erp.Api.Repositories;

public sealed class SqlServerSalesConversionRepository(SqlServerConnectionFactory connections) : ISalesConversionRepository
{
    public async Task<PurchaseConversionResult> ConvertToPurchaseAsync(PurchaseConversionRequest request, CancellationToken cancellationToken)
    {
        await using var connection=connections.Create(); await connection.OpenAsync(cancellationToken); await using var transaction=await connection.BeginTransactionAsync(IsolationLevel.Serializable,cancellationToken); var tx=(SqlTransaction)transaction;
        try
        {
            var replay=await FindPurchaseReplayAsync(connection,tx,request,cancellationToken); if(replay is not null){await transaction.CommitAsync(cancellationToken);return replay;}
            var sourceHeader=await GetSourceHeaderAsync(connection,tx,request.CompanyCode,request.SalesOrderNo,cancellationToken);
            if(sourceHeader.PartnerCode==request.SupplierCode) throw new DomainConflictException("고객을 공급처로 자동 사용할 수 없습니다. 공급처를 다시 선택해 주세요.");
            var supplierName=await RequiredNameAsync(connection,tx,"POC.MA_PARTNER","CD_PARTNER","NM_PARTNER",request.CompanyCode,request.SupplierCode,"선택한 공급처를 찾을 수 없습니다.",cancellationToken);
            var warehouseName=await RequiredNameAsync(connection,tx,"POC.MA_WH","CD_WH","NM_WH",request.CompanyCode,request.WarehouseCode,"선택한 창고를 찾을 수 없습니다.",cancellationToken);
            var requestId=Guid.NewGuid(); var targetId=Guid.NewGuid(); var resultLines=new List<ConversionLineResult>(); var sourceLines=new List<(SourceLine Source,PurchaseConversionLineRequest Requested,Guid TargetLineId,decimal Supply,decimal Vat)>();
            foreach(var requested in request.Lines)
            {
                var source=await GetSourceLineAsync(connection,tx,request.CompanyCode,request.SalesOrderNo,requested.SourceLineNo,cancellationToken);
                var active=await ActivePurchaseQuantityAsync(connection,tx,source.LineId,cancellationToken); var remaining=source.Quantity-active;
                if(requested.Quantity>remaining) throw new DomainConflictException($"수주상세 {requested.SourceLineNo}행의 발주 가능 잔량은 {remaining:0.####}입니다.");
                var supply=decimal.Round(requested.Quantity*requested.UnitPrice,0,MidpointRounding.AwayFromZero); var vat=decimal.Round(supply*.1m,0,MidpointRounding.AwayFromZero);
                sourceLines.Add((source,requested,Guid.NewGuid(),supply,vat)); resultLines.Add(new(sourceHeader.HeaderId,source.LineId,source.LineNo,requested.Quantity,remaining-requested.Quantity));
            }
            var yearMonth=DocumentNumberPolicy.BusinessYearMonth(request.PurchaseOrderDate); var serial=await DocumentNumberSqlAllocator.ReserveAsync(connection,tx,request.CompanyCode,"POR",yearMonth,cancellationToken); var number=DocumentNumberPolicy.Format("POR",yearMonth,serial);
            await ExecuteAsync(connection,tx,"INSERT POC.PUR_POH(ID_POH,ID_CONVERSION_REQUEST,CD_FIRM,NO_PO,DT_PO,CD_PARTNER,NM_PARTNER,CD_EMP,NM_EMP,CD_CURRENCY,RT_EXCHANGE,ST_PO,DC_RMK,CD_USER_REG,TM_REG) VALUES(@target,@request,@firm,@number,@date,@supplier,@supplierName,@employee,@employee,@currency,1,N'신규',@remark,N'API',SYSUTCDATETIME())",cancellationToken,("@target",targetId),("@request",requestId),("@firm",request.CompanyCode),("@number",number),("@date",DateTime.Parse(request.PurchaseOrderDate)),("@supplier",request.SupplierCode),("@supplierName",supplierName),("@employee",request.EmployeeCode),("@currency",request.CurrencyCode),("@remark",$"수주 {request.SalesOrderNo} 전환"));
            for(var index=0;index<sourceLines.Count;index++)
            {
                var row=sourceLines[index];
                await ExecuteAsync(connection,tx,"INSERT POC.PUR_POL(ID_POL,ID_POH,ID_SOURCE_SOH,ID_SOURCE_SOL,NO_SOURCE_SO,NO_SOURCE_LINE,CD_FIRM,NO_PO,NO_LINE,CD_ITEM,NM_ITEM,STND_ITEM,UNIT_ITEM,QT_PO,UM_PO,AM_SUPPLY,AM_VAT,AM_TOTAL,DT_DLV,CD_WH,NM_WH,DC_RMK,CD_USER_REG,TM_REG) VALUES(@lineId,@target,@sourceHeader,@sourceLine,@sourceNo,@sourceLineNo,@firm,@number,@line,@item,@itemName,@standard,@unit,@quantity,@price,@supply,@vat,@total,@due,@warehouse,@warehouseName,@remark,N'API',SYSUTCDATETIME())",cancellationToken,("@lineId",row.TargetLineId),("@target",targetId),("@sourceHeader",sourceHeader.HeaderId),("@sourceLine",row.Source.LineId),("@sourceNo",request.SalesOrderNo),("@sourceLineNo",row.Source.LineNo),("@firm",request.CompanyCode),("@number",number),("@line",index+1),("@item",row.Source.ItemCode),("@itemName",row.Source.ItemName),("@standard",row.Source.Standard),("@unit",row.Source.Unit),("@quantity",row.Requested.Quantity),("@price",row.Requested.UnitPrice),("@supply",row.Supply),("@vat",row.Vat),("@total",row.Supply+row.Vat),("@due",DateTime.Parse(row.Requested.DueDate)),("@warehouse",request.WarehouseCode),("@warehouseName",warehouseName),("@remark",$"원본 {request.SalesOrderNo}/{row.Source.LineNo}"));
            }
            await InsertRequestAsync(connection,tx,requestId,request.CompanyCode,request.RequestKey,"POR",targetId,number,sourceHeader.HeaderId,request.SalesOrderNo,resultLines,cancellationToken);
            await transaction.CommitAsync(cancellationToken); return new(requestId,targetId,number,resultLines,false);
        }
        catch{await transaction.RollbackAsync(cancellationToken);throw;}
    }

    public async Task<WorkOrderConversionResult> ConvertToWorkOrderAsync(WorkOrderConversionRequest request, CancellationToken cancellationToken)
    {
        await using var connection=connections.Create(); await connection.OpenAsync(cancellationToken); await using var transaction=await connection.BeginTransactionAsync(IsolationLevel.Serializable,cancellationToken); var tx=(SqlTransaction)transaction;
        try
        {
            var replay=await FindWorkReplayAsync(connection,tx,request,cancellationToken); if(replay is not null){await transaction.CommitAsync(cancellationToken);return replay;}
            var header=await GetSourceHeaderAsync(connection,tx,request.CompanyCode,request.SalesOrderNo,cancellationToken); var source=await GetSourceLineAsync(connection,tx,request.CompanyCode,request.SalesOrderNo,request.SourceLineNo,cancellationToken);
            var preview=await GetPreviewAsync(connection,tx,request.CompanyCode,source.ItemCode,request.BomVersion,request.RoutingVersion,cancellationToken);
            var lineName=await RequiredNameAsync(connection,tx,"POC.MST_PRODUCTION_LINE","CD_LINE","NM_LINE",request.CompanyCode,request.ProductionLineCode,"선택한 생산라인을 찾을 수 없습니다.",cancellationToken);
            var active=await ActiveWorkQuantityAsync(connection,tx,source.LineId,cancellationToken); var remaining=source.Quantity-active; if(request.Quantity>remaining) throw new DomainConflictException($"수주상세 {request.SourceLineNo}행의 작업지시 가능 잔량은 {remaining:0.####}입니다.");
            var requestId=Guid.NewGuid(); var targetId=Guid.NewGuid(); var yearMonth=DocumentNumberPolicy.BusinessYearMonth(request.WorkOrderDate); var serial=await DocumentNumberSqlAllocator.ReserveAsync(connection,tx,request.CompanyCode,"WMO",yearMonth,cancellationToken); var number=DocumentNumberPolicy.Format("WMO",yearMonth,serial);
            await ExecuteAsync(connection,tx,"INSERT POC.PRT_WO(ID_WO,ID_SOURCE_SOH,ID_SOURCE_SOL,NO_SOURCE_SO,NO_SOURCE_LINE,ID_CONVERSION_REQUEST,CD_FIRM,NO_WO,DT_WO,CD_ITEM,NM_ITEM,STND_ITEM,UNIT_ITEM,QT_WO,QT_RESULT,DT_PLAN_START,DT_PLAN_END,CD_LINE,NM_LINE,ST_WO,YN_URGENT,DC_RMK,CD_USER_REG,TM_REG,CD_USER_AMD,TM_AMD) VALUES(@target,@sourceHeader,@sourceLine,@sourceNo,@sourceLineNo,@request,@firm,@number,@date,@item,@itemName,@standard,@unit,@quantity,0,@start,@end,@line,@lineName,N'미확정','N',@remark,N'API',SYSUTCDATETIME(),N'API',SYSUTCDATETIME())",cancellationToken,("@target",targetId),("@sourceHeader",header.HeaderId),("@sourceLine",source.LineId),("@sourceNo",request.SalesOrderNo),("@sourceLineNo",source.LineNo),("@request",requestId),("@firm",request.CompanyCode),("@number",number),("@date",DateTime.Parse(request.WorkOrderDate)),("@item",source.ItemCode),("@itemName",source.ItemName),("@standard",source.Standard),("@unit",source.Unit),("@quantity",request.Quantity),("@start",DateTime.Parse(request.PlannedStart)),("@end",DateTime.Parse(request.PlannedEnd)),("@line",request.ProductionLineCode),("@lineName",lineName),("@remark",$"수주 {request.SalesOrderNo}/{source.LineNo} 전환"));
            var operations=new List<WorkOrderOperationResult>(); var opIndex=0;
            foreach(var operation in preview.Operations)
            {
                var operationId=Guid.NewGuid(); operations.Add(new(operationId,operation.Sequence,operation.ProcessCode,operation.ProcessName,operation.WorkCenterCode,operation.WorkCenterName,request.Quantity));
                await ExecuteAsync(connection,tx,"INSERT POC.PRT_WOPROC(ID_WOPROC,ID_WO,CD_FIRM,NO_WO,NO_PROC,CD_PROC,NM_PROC,CD_EQUIP,NM_EQUIP,QT_PLAN,QT_RESULT,TM_PLAN_START,TM_PLAN_END,ST_PROC,DC_RMK,CD_USER_REG,TM_REG,CD_USER_AMD,TM_AMD) VALUES(@id,@target,@firm,@number,@sequence,@process,@processName,NULL,NULL,@quantity,0,@start,@end,N'대기',N'',N'API',SYSUTCDATETIME(),N'API',SYSUTCDATETIME())",cancellationToken,("@id",operationId),("@target",targetId),("@firm",request.CompanyCode),("@number",number),("@sequence",operation.Sequence),("@process",operation.ProcessCode),("@processName",operation.ProcessName),("@quantity",request.Quantity),("@start",DateTime.Parse(request.PlannedStart).AddHours(8+opIndex)),("@end",DateTime.Parse(request.PlannedStart).AddHours(9+opIndex))); opIndex++;
            }
            var bills=new List<WorkOrderBillResult>();
            foreach(var bill in preview.Bills)
            {
                var billId=Guid.NewGuid(); var required=bill.BaseQuantity*request.Quantity; bills.Add(new(billId,bill.LineNo,bill.ComponentCode,bill.ComponentName,bill.Unit,bill.BaseQuantity,required));
                await ExecuteAsync(connection,tx,"INSERT POC.PRT_WOBILL(ID_WOBILL,ID_WO,CD_FIRM,NO_WO,NO_BOM_LINE,CD_COMPONENT,NM_COMPONENT,UNIT_COMPONENT,QT_BASE,QT_REQUIRED,CD_USER_REG,TM_REG) VALUES(@id,@target,@firm,@number,@line,@component,@componentName,@unit,@base,@required,N'API',SYSUTCDATETIME())",cancellationToken,("@id",billId),("@target",targetId),("@firm",request.CompanyCode),("@number",number),("@line",bill.LineNo),("@component",bill.ComponentCode),("@componentName",bill.ComponentName),("@unit",bill.Unit),("@base",bill.BaseQuantity),("@required",required));
            }
            var sourceResult=new ConversionLineResult(header.HeaderId,source.LineId,source.LineNo,request.Quantity,remaining-request.Quantity); await InsertRequestAsync(connection,tx,requestId,request.CompanyCode,request.RequestKey,"WMO",targetId,number,header.HeaderId,request.SalesOrderNo,[sourceResult],cancellationToken);
            await transaction.CommitAsync(cancellationToken); return new(requestId,targetId,number,sourceResult,operations,bills,false);
        }
        catch{await transaction.RollbackAsync(cancellationToken);throw;}
    }

    public async Task<SalesConversionMasterPreview> GetWorkOrderPreviewAsync(string companyCode,string salesOrderNo,int sourceLineNo,string bomVersion,string routingVersion,CancellationToken cancellationToken)
    {
        await using var connection=connections.Create(); await connection.OpenAsync(cancellationToken); var source=await GetSourceLineAsync(connection,null,companyCode,salesOrderNo,sourceLineNo,cancellationToken); return await GetPreviewAsync(connection,null,companyCode,source.ItemCode,bomVersion,routingVersion,cancellationToken);
    }

    private static async Task<SalesConversionMasterPreview> GetPreviewAsync(SqlConnection connection,SqlTransaction? tx,string firm,string item,string bomVersion,string routingVersion,CancellationToken ct)
    {
        var bills=new List<ApprovedBomLine>(); await using(var command=new SqlCommand("SELECT line.NO_LINE,line.CD_COMPONENT,line.NM_COMPONENT,line.UNIT_COMPONENT,line.QT_BASE FROM POC.MST_BOM_H header INNER JOIN POC.MST_BOM_L line ON line.ID_BOM=header.ID_BOM WHERE header.CD_FIRM=@firm AND header.CD_ITEM=@item AND header.NO_VERSION=@version AND header.YN_APPROVED='Y' AND header.DT_VALID_FROM<=CAST(GETDATE() AS date) AND (header.DT_VALID_TO IS NULL OR header.DT_VALID_TO>=CAST(GETDATE() AS date)) ORDER BY line.NO_LINE",connection,tx)){command.Parameters.AddWithValue("@firm",firm);command.Parameters.AddWithValue("@item",item);command.Parameters.AddWithValue("@version",bomVersion);await using var reader=await command.ExecuteReaderAsync(ct);while(await reader.ReadAsync(ct))bills.Add(new(reader.GetInt32(0),reader.GetString(1),reader.GetString(2),reader.GetString(3),reader.GetDecimal(4)));}
        if(bills.Count==0) throw new DomainConflictException($"품목 {item}의 승인된 BOM 버전 {bomVersion}을 찾을 수 없습니다.");
        var operations=new List<ApprovedRouteOperation>(); await using(var command=new SqlCommand("SELECT operation.NO_SEQ,operation.CD_PROC,operation.NM_PROC,operation.CD_LINE,operation.NM_LINE,operation.TM_BASE_MIN FROM POC.MST_ROUTING_H header INNER JOIN POC.MST_ROUTING_OP operation ON operation.ID_ROUTING=header.ID_ROUTING WHERE header.CD_FIRM=@firm AND header.CD_ITEM=@item AND header.NO_VERSION=@version AND header.YN_APPROVED='Y' AND header.DT_VALID_FROM<=CAST(GETDATE() AS date) AND (header.DT_VALID_TO IS NULL OR header.DT_VALID_TO>=CAST(GETDATE() AS date)) ORDER BY operation.NO_SEQ",connection,tx)){command.Parameters.AddWithValue("@firm",firm);command.Parameters.AddWithValue("@item",item);command.Parameters.AddWithValue("@version",routingVersion);await using var reader=await command.ExecuteReaderAsync(ct);while(await reader.ReadAsync(ct))operations.Add(new(reader.GetInt32(0),reader.GetString(1),reader.GetString(2),reader.GetString(3),reader.GetString(4),reader.GetDecimal(5)));}
        if(operations.Count==0) throw new DomainConflictException($"품목 {item}의 승인된 공정경로 버전 {routingVersion}을 찾을 수 없습니다."); return new(item,bomVersion,routingVersion,bills,operations);
    }

    private static async Task<SourceHeader> GetSourceHeaderAsync(SqlConnection connection,SqlTransaction? tx,string firm,string number,CancellationToken ct){await using var command=new SqlCommand($"SELECT ID_SOH,CD_PARTNER FROM POC.SAL_SOH {(tx is null?"":"WITH (UPDLOCK,HOLDLOCK)")} WHERE CD_FIRM=@firm AND NO_SO=@number",connection,tx);command.Parameters.AddWithValue("@firm",firm);command.Parameters.AddWithValue("@number",number);await using var reader=await command.ExecuteReaderAsync(ct);if(!await reader.ReadAsync(ct))throw new DomainConflictException("원본 수주를 찾을 수 없습니다.");return new(reader.GetGuid(0),reader.GetString(1));}
    private static async Task<SourceLine> GetSourceLineAsync(SqlConnection connection,SqlTransaction? tx,string firm,string number,int line,CancellationToken ct){await using var command=new SqlCommand($"SELECT ID_SOL,NO_LINE,CD_ITEM,NM_ITEM,STND_ITEM,UNIT_ITEM,QT_SO FROM POC.SAL_SOL {(tx is null?"":"WITH (UPDLOCK,HOLDLOCK)")} WHERE CD_FIRM=@firm AND NO_SO=@number AND NO_LINE=@line",connection,tx);command.Parameters.AddWithValue("@firm",firm);command.Parameters.AddWithValue("@number",number);command.Parameters.AddWithValue("@line",line);await using var reader=await command.ExecuteReaderAsync(ct);if(!await reader.ReadAsync(ct))throw new DomainConflictException($"수주상세 {line}행을 찾을 수 없습니다.");return new(reader.GetGuid(0),reader.GetInt32(1),reader.GetString(2),reader.GetString(3),reader.GetString(4),reader.GetString(5),reader.GetDecimal(6));}
    private static async Task<string> RequiredNameAsync(SqlConnection connection,SqlTransaction tx,string table,string codeColumn,string nameColumn,string firm,string code,string error,CancellationToken ct){await using var command=new SqlCommand($"SELECT {nameColumn} FROM {table} WHERE CD_FIRM=@firm AND {codeColumn}=@code AND YN_USE='Y'",connection,tx);command.Parameters.AddWithValue("@firm",firm);command.Parameters.AddWithValue("@code",code);return await command.ExecuteScalarAsync(ct) as string??throw new DomainConflictException(error);}
    private static async Task<decimal> ActivePurchaseQuantityAsync(SqlConnection connection,SqlTransaction tx,Guid sourceLineId,CancellationToken ct)=>await ScalarDecimalAsync(connection,tx,"SELECT COALESCE(SUM(line.QT_PO),0) FROM POC.PUR_POL line INNER JOIN POC.PUR_POH header ON header.ID_POH=line.ID_POH WHERE line.ID_SOURCE_SOL=@source AND header.ST_PO NOT IN(N'취소',N'Cancelled')",sourceLineId,ct);
    private static async Task<decimal> ActiveWorkQuantityAsync(SqlConnection connection,SqlTransaction tx,Guid sourceLineId,CancellationToken ct)=>await ScalarDecimalAsync(connection,tx,"SELECT COALESCE(SUM(QT_WO),0) FROM POC.PRT_WO WHERE ID_SOURCE_SOL=@source AND ST_WO NOT IN(N'취소',N'Cancelled')",sourceLineId,ct);
    private static async Task<decimal> ScalarDecimalAsync(SqlConnection connection,SqlTransaction tx,string sql,Guid source,CancellationToken ct){await using var command=new SqlCommand(sql,connection,tx);command.Parameters.AddWithValue("@source",source);return Convert.ToDecimal(await command.ExecuteScalarAsync(ct));}

    private static async Task InsertRequestAsync(SqlConnection connection,SqlTransaction tx,Guid requestId,string firm,string key,string type,Guid targetId,string targetNo,Guid sourceHeaderId,string sourceNo,IReadOnlyList<ConversionLineResult> lines,CancellationToken ct){await ExecuteAsync(connection,tx,"INSERT POC.DOC_CONVERSION_REQUEST(ID_REQUEST,CD_FIRM,REQUEST_KEY,CONVERSION_TYPE,ID_TARGET,NO_TARGET,ST_REQUEST,CD_USER_REG,TM_REG) VALUES(@id,@firm,@key,@type,@target,@number,N'완료',N'API',SYSUTCDATETIME())",ct,("@id",requestId),("@firm",firm),("@key",key),("@type",type),("@target",targetId),("@number",targetNo));foreach(var line in lines)await ExecuteAsync(connection,tx,"INSERT POC.DOC_CONVERSION_REQUEST_LINE(ID_REQUEST,ID_SOURCE_SOH,ID_SOURCE_SOL,NO_SOURCE_SO,NO_SOURCE_LINE,QT_CONVERTED) VALUES(@request,@sourceHeader,@sourceLine,@sourceNo,@line,@quantity)",ct,("@request",requestId),("@sourceHeader",sourceHeaderId),("@sourceLine",line.SourceLineId),("@sourceNo",sourceNo),("@line",line.SourceLineNo),("@quantity",line.ConvertedQuantity));}
    private static async Task<PurchaseConversionResult?> FindPurchaseReplayAsync(SqlConnection connection,SqlTransaction tx,PurchaseConversionRequest request,CancellationToken ct){var row=await FindRequestAsync(connection,tx,request.CompanyCode,"POR",request.RequestKey,ct);if(row is null)return null;var lines=await ReplayLinesAsync(connection,tx,row.Value.RequestId,"POR",ct);return new(row.Value.RequestId,row.Value.TargetId,row.Value.Number,lines,true);}
    private static async Task<WorkOrderConversionResult?> FindWorkReplayAsync(SqlConnection connection,SqlTransaction tx,WorkOrderConversionRequest request,CancellationToken ct){var row=await FindRequestAsync(connection,tx,request.CompanyCode,"WMO",request.RequestKey,ct);if(row is null)return null;var lines=await ReplayLinesAsync(connection,tx,row.Value.RequestId,"WMO",ct);var source=lines.Single();var preview=await GetPreviewAsync(connection,tx,request.CompanyCode,(await GetSourceLineAsync(connection,tx,request.CompanyCode,request.SalesOrderNo,request.SourceLineNo,ct)).ItemCode,request.BomVersion,request.RoutingVersion,ct);var operations=preview.Operations.Select(x=>new WorkOrderOperationResult(Guid.Empty,x.Sequence,x.ProcessCode,x.ProcessName,x.WorkCenterCode,x.WorkCenterName,source.ConvertedQuantity)).ToArray();var bills=preview.Bills.Select(x=>new WorkOrderBillResult(Guid.Empty,x.LineNo,x.ComponentCode,x.ComponentName,x.Unit,x.BaseQuantity,x.BaseQuantity*source.ConvertedQuantity)).ToArray();return new(row.Value.RequestId,row.Value.TargetId,row.Value.Number,source,operations,bills,true);}
    private static async Task<(Guid RequestId,Guid TargetId,string Number)?> FindRequestAsync(SqlConnection connection,SqlTransaction tx,string firm,string type,string key,CancellationToken ct){await using var command=new SqlCommand("SELECT ID_REQUEST,ID_TARGET,NO_TARGET FROM POC.DOC_CONVERSION_REQUEST WITH(UPDLOCK,HOLDLOCK) WHERE CD_FIRM=@firm AND CONVERSION_TYPE=@type AND REQUEST_KEY=@key",connection,tx);command.Parameters.AddWithValue("@firm",firm);command.Parameters.AddWithValue("@type",type);command.Parameters.AddWithValue("@key",key);await using var reader=await command.ExecuteReaderAsync(ct);return await reader.ReadAsync(ct)?(reader.GetGuid(0),reader.GetGuid(1),reader.GetString(2)):null;}
    private static async Task<IReadOnlyList<ConversionLineResult>> ReplayLinesAsync(SqlConnection connection,SqlTransaction tx,Guid requestId,string type,CancellationToken ct){var rows=new List<(Guid HeaderId,Guid LineId,int LineNo,decimal Converted,decimal SourceQuantity)>();await using(var command=new SqlCommand("SELECT line.ID_SOURCE_SOH,line.ID_SOURCE_SOL,line.NO_SOURCE_LINE,line.QT_CONVERTED,source.QT_SO FROM POC.DOC_CONVERSION_REQUEST_LINE line INNER JOIN POC.SAL_SOL source ON source.ID_SOL=line.ID_SOURCE_SOL WHERE line.ID_REQUEST=@request ORDER BY line.NO_SOURCE_LINE",connection,tx)){command.Parameters.AddWithValue("@request",requestId);await using var reader=await command.ExecuteReaderAsync(ct);while(await reader.ReadAsync(ct))rows.Add((reader.GetGuid(0),reader.GetGuid(1),reader.GetInt32(2),reader.GetDecimal(3),reader.GetDecimal(4)));}var result=new List<ConversionLineResult>();foreach(var row in rows){var active=type=="POR"?await ActivePurchaseQuantityAsync(connection,tx,row.LineId,ct):await ActiveWorkQuantityAsync(connection,tx,row.LineId,ct);result.Add(new(row.HeaderId,row.LineId,row.LineNo,row.Converted,row.SourceQuantity-active));}return result;}

    private static async Task ExecuteAsync(SqlConnection connection,SqlTransaction tx,string sql,CancellationToken ct,params (string Name,object Value)[] parameters){await using var command=new SqlCommand(sql,connection,tx);foreach(var parameter in parameters)command.Parameters.AddWithValue(parameter.Name,parameter.Value);await command.ExecuteNonQueryAsync(ct);}
    private sealed record SourceHeader(Guid HeaderId,string PartnerCode);
    private sealed record SourceLine(Guid LineId,int LineNo,string ItemCode,string ItemName,string Standard,string Unit,decimal Quantity);
}
